name: 04 - Uso de actions
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./my-app
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      #- name: printing folders
      #  run: ls

      - name: node setup
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: install dependencies
        run: npm ci
        # working-directory: ./my-app
      
      - name: run unit test
        run: npm run test
        # working-directory: ./my-app
        